spring.application.name=dailityHabits

spring.datasource.url=${DB_URL:jdbc:sqlserver://devops-work-db.database.windows.net:1433;\
  database=devops-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.\
  database.windows.net;loginTimeout=3}
spring.datasource.username=${DB_USERNAME:userRoot@devops-work-db}
spring.datasource.password=${DB_PASSWORD:dev0psisashit!}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secretKey=${JWT_SECRET_KEY:70d1510afecf511db95fcb07aa998b16b8ccb0cc0c8ce133fe72725a74d92c6b}
jwt.expiration=${JWT_EXPIRATION:3600000}
